### ISSUE TITLE
Checklist for Lynn

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/nestflix.fun#8]
- [x] 50 million movies
- [x] logo
- [x] favicon
- [x] footer
- [x] ~about page~ Combine with contribute page
- [x] contribution instructions + Github issue template or Netlify form?
- [x] header collage for landing page
- [x] ~prefers-reduced-motion~ Only movement is the transition for each card and that feels ok
- [x] no-js
- [x] make sure grid feels good for various # of items
- [x] ~carousel for categories with lots of items?~ Not gonna do this
- [x] lazy img loading? #19 
- [x] choose featured movie(s) on homepage and style them better
- [x] decide on and buy domain
- [x] cross browser testing
- [x] responsive testing
- [x] tab navigation
- [x] image optimization
- [x] fonts (Just going to use system ones)
- [x] analytics
- [x] social images #19 
- [x] hero text for huge screens
- [x] alt tags for images
- [x] widths and heights for images
- [x] ~dark mode~ (Always dark mode)
- [x] treat tags as categories; add labels for keywords
- [x] ~"recently left Nestflix" list~ Not gonna do this
- [x] ~Consistent use of single quotes for titles in descriptions~ (using `<em>` instead)
- [x] Finesse descriptions + logo sizes
- [x] More specific categories (so fewer items in each category)
- [x] 404 page (good enough for now)
- [x] user icon + page
- [x] better breakpoints for movie stills
